CREATE DATABASE ESPACIO;
USE ESPACIO;

CREATE TABLE NAU(
NUM_TRIPULANTS VARCHAR(20),
NOM_NAVE VARCHAR(20) PRIMARY KEY,
VELOCITAT_MAX INT
);
CREATE TABLE PLANETA(
CODI_PLANETA INT PRIMARY KEY,
GALAXIA VARCHAR(20),
NOM_PLANETA VARCHAR(20)
);
CREATE TABLE TEMPORADA(
NUM_TEMPORADA INT PRIMARY KEY,
DESCRIPCIO VARCHAR(20),
DATA_INICI DATE
);
CREATE TABLE CAPITOL(
NUM_ORDRE INT,
SINOPSI VARCHAR(20),
TITOL VARCHAR(20),
NUM_TEMPORADA INT,
FOREIGN KEY (NUM_TEMPORADA) REFERENCES TEMPORADA(NUM_TEMPORADA),
PRIMARY KEY(NUM_ORDRE, NUM_TEMPORADA)
);
CREATE TABLE VULCA(
NOM_PERSONATGE VARCHAR(20),
MENTOR VARCHAR(20),
NUM_CAPITOL INT,
NUM_TEMPORADA INT,
FOREIGN KEY (NUM_CAPITOL) REFERENCES CAPITOL(NUM_ORDRE),
FOREIGN KEY (NUM_TEMPORADA) REFERENCES TEMPORADA(NUM_TEMPORADA),
PRIMARY KEY (NOM_PERSONATGE, NUM_CAPITOL, NUM_TEMPORADA)
);
CREATE TABLE HUMA(
NOM_PERSONATGE VARCHAR(20) PRIMARY KEY,
DATA_NAIX DATE
);
CREATE TABLE KLINGON(
NOM_PERSONATGE VARCHAR(20),
DATA_ULTIM_COMBAT DATE,
NUM_CAPITOL INT,
NUM_TEMPORADA INT,
FOREIGN KEY (NUM_TEMPORADA) REFERENCES TEMPORADA(NUM_TEMPORADA),
FOREIGN KEY (NUM_CAPITOL) REFERENCES CAPITOL(NUM_ORDRE),
PRIMARY KEY(NOM_PERSONATGE, NUM_CAPITOL, NUM_TEMPORADA)
);
CREATE TABLE APAREIX(
NOM_HUMA VARCHAR(20),
NUM_CAPITOL INT,
NUM_TEMPORADA INT,
FOREIGN KEY (NOM_HUMA) REFERENCES HUMA(NOM_PERSONATGE),
FOREIGN KEY (NUM_TEMPORADA) REFERENCES TEMPORADA(NUM_TEMPORADA),
FOREIGN KEY (NUM_CAPITOL) REFERENCES CAPITOL(NUM_ORDRE),
PRIMARY KEY (NUM_TEMPORADA, NOM_HUMA, NUM_CAPITOL)
);
CREATE TABLE VISITA (
NOM_NAVE VARCHAR(20),
CODI_PLANETA INT,
NUM_CAPITOL INT,
NUM_TEMPORADA INT,
FOREIGN KEY(NOM_NAVE) REFERENCES NAU(NOM_NAVE),
FOREIGN KEY(CODI_PLANETA) REFERENCES PLANETA(CODI_PLANETA),
FOREIGN KEY (NUM_TEMPORADA) REFERENCES TEMPORADA(NUM_TEMPORADA),
FOREIGN KEY (NUM_CAPITOL) REFERENCES CAPITOL(NUM_ORDRE),
PRIMARY KEY(NOM_NAVE, CODI_PLANETA, NUM_CAPITOL, NUM_TEMPORADA)

);
