CREATE DATABASE ESCOLA;
USE ESCOLA;

CREATE TABLE POBLACIONS(
    NOM VARCHAR(20) PRIMARY KEY,
    HABITANTS INT
);

CREATE TABLE ACTIVITATS(
    NOM VARCHAR(20) PRIMARY KEY
);

CREATE TABLE ESCOLES(
    CODI INT PRIMARY KEY AUTO_INCREMENT,
    NOM VARCHAR(20),
    NOM_POBLACIO VARCHAR(20),
    FOREIGN KEY (NOM_POBLACIO) REFERENCES POBLACIONS(NOM)
);

CREATE TABLE ALUMNES(
    CODI INT PRIMARY KEY AUTO_INCREMENT,
    NOM VARCHAR(20),
    COGNOMS VARCHAR(20),
    TELEFON INT,
    CODI_ESCOLA INT DEFAULT 2222,
    NOM_POBLACIO VARCHAR(20) DEFAULT "Terrassa",
    FOREIGN KEY (CODI_ESCOLA) REFERENCES ESCOLES(CODI),
    FOREIGN KEY (NOM_POBLACIO) REFERENCES POBLACIONS(NOM)
);

CREATE TABLE ACTIVITATS_ESCOLES(
    CODI_ESCOLA INT,
    NOM_ACTIVITAT VARCHAR(20),
    PLACES INT,
    PUNTUACIO INT CHECK (PUNTUACIO >= 0 AND PUNTUACIO <= 10),
    PRIMARY KEY (CODI_ESCOLA, NOM_ACTIVITAT),
    FOREIGN KEY (CODI_ESCOLA) REFERENCES ESCOLES(CODI),
    FOREIGN KEY (NOM_ACTIVITAT) REFERENCES ACTIVITATS(NOM)
);
ALTER TABLE ACTIVITATS_ESCOLES CHANGE PLACES VACANTS INT;
INSERT INTO POBLACIONS VALUES ('Terrassa', 9000000);
INSERT INTO POBLACIONS VALUES ('Sabadell', 300000);
INSERT INTO POBLACIONS VALUES ('Barcelona', 1500000);
INSERT INTO POBLACIONS VALUES ('Girona', 100000);
INSERT INTO POBLACIONS VALUES ('Lleida', 150000);
INSERT INTO POBLACIONS VALUES ('Tarragona', 130000);
INSERT INTO ACTIVITATS VALUES ('Futbol');
INSERT INTO ACTIVITATS VALUES ('Natació');
INSERT INTO ACTIVITATS VALUES ('Teatre');
INSERT INTO ESCOLES VALUES ('COPERNIC', 'Terrassa');
INSERT INTO ESCOLES VALUES ('LA SALLE', 'Sabadell');
INSERT INTO ESCOLES VALUES ('MONTESSORI', 'Barcelona');
INSERT INTO ALUMNES VALUES (1, 'JOSE', 'DURAN', 611478940, 1, 'Terrassa', 12);
INSERT INTO ALUMNES VALUES (2, 'MARC', 'ARIAS', 665465110, 1, 'Terrassa', 9);
INSERT INTO ALUMNES VALUES (3, 'LAURA', 'MARTI', 612345678, 2, 'Sabadell', 10);
INSERT INTO ACTIVITATS_ESCOLES VALUES (1, 'Futbol', 20, 8);
INSERT INTO ACTIVITATS_ESCOLES VALUES (2, 'Natació', 15, 9);
INSERT INTO ACTIVITATS_ESCOLES VALUES (3, 'Teatre', 10, 7);
ALTER TABLE ALUMNES ADD EDAT INT CHECK (EDAT >= 3);
ALTER TABLE POBLACIONS RENAME TO POBLACIO;
ALTER TABLE ESCOLES RENAME TO ESCOLA;
ALTER TABLE ACTIVITATS RENAME TO ACTIVITAT;
ALTER TABLE ACTIVITATS_ESCOLES RENAME TO ACTIVITAT_ESCOLAR;
ALTER TABLE ACTIVITAT_ESCOLAR MODIFY PUNTUACIO INT DEFAULT 5;
SELECT * FROM ALUMNES;
DELETE FROM ALUMNES WHERE (EDAT >10 AND EDAT <13);