CREATE DATABASE ESCOLA;
USE ESCOLA;

CREATE TABLE POBLACIONS(
    NOM VARCHAR(20) PRIMARY KEY,
    HABITANTS INT
);

CREATE TABLE ACTIVITATS(
    NOM VARCHAR(20) PRIMARY KEY
);

CREATE TABLE ESCOLES(
    CODI INT PRIMARY KEY AUTO_INCREMENT,
    NOM VARCHAR(20),
    NOM_POBLACIO VARCHAR(20),
    FOREIGN KEY (NOM_POBLACIO) REFERENCES POBLACIONS(NOM)
);

CREATE TABLE ALUMNES(
    CODI INT PRIMARY KEY AUTO_INCREMENT,
    NOM VARCHAR(20),
    COGNOMS VARCHAR(20),
    TELEFON INT,
    CODI_ESCOLA INT DEFAULT(2222),
    NOM_POBLACIO VARCHAR(20) DEFAULT("TERRASSA"),
    FOREIGN KEY (CODI_ESCOLA) REFERENCES ESCOLES(CODI),
    FOREIGN KEY (NOM_POBLACIO) REFERENCES POBLACIONS(NOM)
);

CREATE TABLE ACTIVITATS_ESCOLES(
    CODI_ESCOLA INT,
    NOM_ACTIVITAT VARCHAR(20),
    PLACES INT,
    PUNTUACIO INT CHECK (PUNTUACIO >= 0 AND PUNTUACIO <= 10),
    PRIMARY KEY (CODI_ESCOLA, NOM_ACTIVITAT),
    FOREIGN KEY (CODI_ESCOLA) REFERENCES ESCOLES(CODI),
    FOREIGN KEY (NOM_ACTIVITAT) REFERENCES ACTIVITATS(NOM)
);
INSERT INTO POBLACIONS VALUES("TERRASSA", 12000);
INSERT INTO ESCOLES VALUES(2222, "COPERNIC", "TERRASSA");
INSERT INTO ALUMNES VALUES(22222, "JOSE", "DURAN", 611478940, 2222, "TERRASSA");
INSERT INTO ALUMNES(NOM,COGNOMS,TELEFON) VALUES("MARC", "ARIAS", 665465110);
select * FROM ALUMNES;