CREATE DATABASE MODIFICAR_CLASE;
USE MODIFICAR_CLASE;

CREATE TABLE EMPLEAT(
CODI INT(4) PRIMARY KEY,
NOM VARCHAR(15),
COGNOMS VARCHAR(30),
TREBALL VARCHAR(10),
CODI_CARREC INT(4),
DATA_CONTRACTE DATE,
SALARI INT(7),
COMISSIO INT(7),
DEPARTAMENT INT(2)
);
ALTER TABLE EMPLEAT MODIFY SALARI DECIMAL(7,2) NOT NULL;

CREATE TABLE DEPARTAMENT(
NUMERO_DEP INT(2),
NOM_DEP CHAR(9) PRIMARY KEY,
LOCALITZACIO CHAR(10)
);
CREATE TABLE DEPARTAMENT2(
NUMERO_DEP INT(2) PRIMARY KEY,
NOM_DEP CHAR(9),
LOCALITZACIO CHAR(10)
);
CREATE TABLE EMPLEAT2(
CODI INT(4),
NOM VARCHAR(15),
COGNOMS VARCHAR(30),
TREBALL VARCHAR(10),
CODI_CARREC INT(4),
DATA_CONTRACTE DATE,
SALARI INT(7),
COMISSIO INT(7),
DEPARTAMENT INT(2),
FOREIGN KEY (DEPARTAMENT) REFERENCES DEPARTAMENT2(NUMERO_DEP),
PRIMARY KEY (SALARI, COMISSIO)
);