DROP DATABASE IF EXISTS TALLER_MECANICO;
CREATE DATABASE TALLER_MECANICO;
USE TALLER_MECANICO;

-- Tabla de Repuestos (Recanvis)
CREATE TABLE RECANVIS (
    CODI_RECANVI INT PRIMARY KEY,
    NOM VARCHAR(50),
    MODEL_COTXE VARCHAR(50),
    PREU_BASE DOUBLE,
    QUANTITAT INT,
    PREU_TOTAL_IVA DOUBLE,
    ESTADO_STOCK VARCHAR(20)
);


-- Tabla de Auditoría (Bitácora)
CREATE TABLE LOG_INVENTARI (
    ID_LOG INT AUTO_INCREMENT PRIMARY KEY,
    DATA_MOVIMENT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    USUARI VARCHAR(50) NOT NULL,
    DESCRIPCIO VARCHAR(100) NOT NULL
);

-- Tabla de Uso de Repuestos en reparaciones
CREATE TABLE USO_RECANVIS (
    ID_USO INT AUTO_INCREMENT PRIMARY KEY,
    CODI_RECANVI INT,
    QUANTITAT INT,
    DATA_US DATE
);
DELIMITER //
CREATE FUNCTION PREU_TOTAL_IVA(PREU_BASE DOUBLE, QUANTITAT INT)
RETURNS DOUBLE DETERMINISTIC
BEGIN
	RETURN (PREU_BASE * QUANTITAT) * 1.21;
END //
DELIMITER ;

INSERT INTO RECANVIS (CODI_RECANVI,PREU_BASE, QUANTITAT, PREU_TOTAL_IVA) VALUES (90,40.5,5,PREU_TOTAL_IVA(40.5,5));
INSERT INTO RECANVIS (CODI_RECANVI, NOM, MODEL_COTXE, PREU_BASE, QUANTITAT, PREU_TOTAL_IVA, ESTADO_STOCK) 
VALUES (1, 'Pastillas de freno', 'Opel Corsa C 2005', 45.00, 10, PREU_TOTAL_IVA(45.00, 10), ESTADO_STOCK(10));

INSERT INTO RECANVIS (CODI_RECANVI, NOM, MODEL_COTXE, PREU_BASE, QUANTITAT, PREU_TOTAL_IVA, ESTADO_STOCK) 
VALUES (2, 'Bomba de agua', 'Opel Corsa C 2005', 85.50, 2, PREU_TOTAL_IVA(85.50, 2), ESTADO_STOCK(2));

INSERT INTO RECANVIS (CODI_RECANVI, NOM, MODEL_COTXE, PREU_BASE, QUANTITAT, PREU_TOTAL_IVA, ESTADO_STOCK) 
VALUES (3, 'Filtro de aceite', 'Universal', 15.00, 0, PREU_TOTAL_IVA(15.00, 0), ESTADO_STOCK(0));
SELECT * FROM RECANVIS;

DELIMITER //
CREATE TRIGGER RECANVIS_LOG AFTER UPDATE ON RECANVIS
FOR EACH ROW
BEGIN
	INSERT INTO LOG_INVENTARI(USUARI, DESCRIPCIO) 
    VALUES (current_user(), CONCAT('SE MODIFICO EL STOCK DEL REPUESTO: ', NEW.NOM));
END // 
DELIMITER ;

UPDATE RECANVIS 
SET QUANTITAT = 45
WHERE CODI_RECANVI = 1;

SELECT * FROM LOG_INVENTARI;
DELIMITER //
CREATE TRIGGER CONTROL_STOCK BEFORE INSERT ON USO_RECANVIS
FOR EACH ROW
BEGIN
	DECLARE STOCK_ACTUAL INT;
    SELECT QUANTITAT INTO STOCK_ACTUAL FROM RECANVIS
    WHERE CODI_RECANVI = NEW.CODI_RECANVI;
    
	IF NEW.QUANTITAT > STOCK_ACTUAL THEN
		SET NEW.QUANTITAT = STOCK_ACTUAL;
       /* SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = '¡Epa loco! No hay tanto stock para este repuesto';*/
	END IF;
END //
DELIMITER ;


INSERT INTO USO_RECANVIS (CODI_RECANVI, QUANTITAT, DATA_US) 
VALUES (1, 50, '2026-05-28');

SELECT * FROM USO_RECANVIS;

DELIMITER //
CREATE FUNCTION ESTADO_STOCK(QUANTITAT INT)
RETURNS VARCHAR(20) DETERMINISTIC
BEGIN
	IF QUANTITAT = 0 THEN
		RETURN 'CRITICO COMPRAR YA';
	ELSEIF QUANTITAT >= 1 AND QUANTITAT <=5 THEN
		RETURN 'PILAS QUEDA POCO';
	ELSE 
		RETURN 'ESTAMOS BIEN';
	END IF;
    END //
DELIMITER ;
INSERT INTO RECANVIS (CODI_RECANVI,QUANTITAT, ESTADO_STOCK) VALUES (93,0, ESTADO_STOCK(0));

SELECT * FROM RECANVIS;

DELIMITER //
CREATE TRIGGER CUIDA_PRECIO BEFORE UPDATE ON RECANVIS
FOR EACH ROW
BEGIN 
	IF NEW.PREU_BASE < 0 THEN
		SET NEW.PREU_BASE = OLD.PREU_BASE;
	end if;
END // 
DELIMITER ;

INSERT INTO RECANVIS(CODI_RECANVI, PREU_BASE) VALUES ( 9238 , 212);
UPDATE RECANVIS
SET PREU_BASE = -985
WHERE CODI_RECANVI = 9238;
SELECT * FROM RECANVIS;

DELIMITER //
CREATE TRIGGER DESCUENTA_STOCK AFTER INSERT ON USO_RECANVIS
FOR EACH ROW
BEGIN
	UPDATE RECANVIS
    SET QUANTITAT = QUANTITAT - NEW.QUANTITAT
    WHERE CODI_RECANVI = NEW.CODI_RECANVI;
END // 
DELIMITER ;
SELECT NOM, QUANTITAT FROM RECANVIS WHERE CODI_RECANVI = 2;

-- 2. Ahora, el mecánico saca 1 Bomba de agua para reparar un Corsa hoy.
-- Al hacer este INSERT, tu trigger DESCUENTA_STOCK se va a activar por debajo de la mesa.
INSERT INTO USO_RECANVIS (CODI_RECANVI, QUANTITAT, DATA_US) 
VALUES (2, 1, '2026-05-28');

-- 3. Revisamos el historial de uso para confirmar que sí se anotó el gasto.
SELECT * FROM USO_RECANVIS;

-- 4. Volvemos a revisar el inventario central... 
-- ¡El fatality! La QUANTITAT ahora debería ser 1 en vez de 2.
SELECT NOM, QUANTITAT FROM RECANVIS WHERE CODI_RECANVI = 2;