DROP DATABASE IF EXISTS SIMULACRE_EXAMEN;
CREATE DATABASE SIMULACRE_EXAMEN;
USE SIMULACRE_EXAMEN;

CREATE TABLE NUMEROS(
NUM INT,
SIGNE VARCHAR(20)
);

CREATE TABLE TENDA(
PREU DOUBLE,
DESCOMPTE DOUBLE,
PREU_FINAL DOUBLE
);


DELIMITER //
CREATE FUNCTION SIGNE(NUM INT)
RETURNS VARCHAR(20) DETERMINISTIC
BEGIN
    IF NUM < 0 THEN
		RETURN 'NEGATIU';
	ELSEIF NUM > 0 THEN
		RETURN 'POSITIU';
	ELSE
		RETURN 'ZERO';
	END IF;
		
END //
DELIMITER ;

INSERT INTO NUMEROS (NUM, SIGNE) VALUES(-1, SIGNE(-1));
INSERT INTO NUMEROS (NUM, SIGNE) VALUES(3, SIGNE(3));
INSERT INTO NUMEROS (NUM, SIGNE) VALUES(0, SIGNE(0));


SELECT * FROM NUMEROS;

DELIMITER //

CREATE FUNCTION PREU_FINAL(PREU DOUBLE, DESCOMPTE INT)
RETURNS DOUBLE DETERMINISTIC
BEGIN
	RETURN PREU - ((PREU * DESCOMPTE) / 100);
END // 
DELIMITER ;

INSERT INTO TENDA (PREU, DESCOMPTE, PREU_FINAL) VALUES (200, 25, PREU_FINAL(200, 25));

SELECT * FROM TENDA;

CREATE TABLE ALUMNE (
NOTA DOUBLE,
QUAL_NOTA VARCHAR(20),
NOM VARCHAR(20),
COGNOM VARCHAR(20),
APTE VARCHAR(20),
BONO VARCHAR(20)

);


DELIMITER //
CREATE FUNCTION QUALIFICACIO(NOTA DOUBLE)
RETURNS VARCHAR(20) DETERMINISTIC
BEGIN 
	 IF NOTA >= 9 THEN
        RETURN 'EXCELENT';
    ELSEIF NOTA >= 7 THEN
        RETURN 'NOTABLE';
    ELSEIF NOTA >= 5 THEN
        RETURN 'BE';
    ELSE
        RETURN 'INSUFICIENT';
    END IF;

END //
DELIMITER ;

INSERT INTO ALUMNE (NOTA, QUAL_NOTA) VALUES (5, QUALIFICACIO(5));

SELECT * FROM ALUMNE;


DELIMITER // 
CREATE FUNCTION CALCULA_BONO(NOTA double)
RETURNS VARCHAR(50) DETERMINISTIC
BEGIN
	IF NOTA >= 9 THEN
		RETURN '5O PALOS';
	ELSEIF NOTA >= 7 THEN
		RETURN '20 PALOS';
	ELSE
		RETURN 'NADA PAPA';
	END IF;

END //
DELIMITER ;

INSERT INTO ALUMNE (NOTA, BONO) VALUES (5, CALCULA_BONO(5));

SELECT NOTA, BONO FROM ALUMNE;

DELIMITER //
CREATE TRIGGER ACOMODA_NOTA BEFORE INSERT ON ALUMNE 
FOR EACH ROW
BEGIN
	IF NEW.NOTA < 0 THEN
		SET NEW.NOTA = 0;
	END IF;
END //

DELIMITER ;

INSERT INTO ALUMNE (NOTA, NOM) VALUES (-5, 'Jose');

SELECT * FROM ALUMNE;
