CREATE DATABASE SERIE;
USE SERIE;

CREATE TABLE SERIE(
NOM VARCHAR(20) PRIMARY KEY,
TIPO VARCHAR(20),
PUBLIC VARCHAR(20)
);
CREATE TABLE CONTINUACIO(
foreign key (NOM_SERIE) REFERENCES SERIE(NOM),
NOM_SERIE VARCHAR(20) PRIMARY KEY
);
CREATE TABLE CAPITOLS(
NUMERO INT,
RESUM VARCHAR(20),
SERIE_CODI VARCHAR(20),
foreign key (SERIE_CODI) REFERENCES SERIE(NOM),
primary key(NUMERO, SERIE_CODI)
);
CREATE TABLE PLATO(
CODI INT PRIMARY KEY,
M2 INT
);
CREATE TABLE DATA_1(
DATA_1 DATETIME PRIMARY KEY
);
CREATE TABLE QUE_TE(
DATA_1 DATETIME,
CODI_PLATO INT,
NUMERO_CAPITOL INT,
primary key(DATA_1, PLATO),
FOREIGN KEY (DATA_1) REFERENCES DATA_1(DATA_1),
FOREIGN KEY (CODI_PLATO) REFERENCES PLATO(CODI),
FOREIGN KEY (NUMERO_CAPITOL) REFERENCES CAPITOLS(NUMERO)
);
CREATE TABLE CADENA_TELEVISIO(
NOM VARCHAR(20) PRIMARY KEY,
AMBIT VARCHAR(20)
);
CREATE TABLE ESTA(
NOM_CADENA VARCHAR(20),
NOM_SERIE VARCHAR(20),
foreign key (NOM_CADENA) references CADENA_TELEVISIO(NOM),
FOREIGN KEY (NOM_SERIE) REFERENCES SERIE(NOM),
PRIMARY key(NOM_CADENA, NOM_SERIE)
);

